"""recipes.source_book / recipes.source_page (Chunk 3.7b)

Revision ID: 9b903c88b3aa
Revises: bf3919bfcbd9
Create Date: 2026-09-06 16:24:27.537181

First real migration after the Alembic baseline — adds the two nullable free-text source
provenance columns to the existing ``recipes`` table (see CLAUDE.md > Data Model > recipes
and > Build Phases > Phase 3 > Chunk 3.7b). Nullable with no default, so it applies to a
populated table without touching existing rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b903c88b3aa'
down_revision: Union[str, Sequence[str], None] = 'bf3919bfcbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_book', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_page', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('source_page')
        batch_op.drop_column('source_book')

    # ### end Alembic commands ###
