"""baseline schema (Phase 1 through Chunk 3.5 tables)

Revision ID: bf3919bfcbd9
Revises:
Create Date: 2026-09-06 16:14:36.948616

Alembic bootstrap baseline — see CLAUDE.md > Code Architecture & Maintainability > Migrations
and > Build Phases > Phase 3 > Chunk 3.7a. This reproduces the exact schema that
``Base.metadata.create_all()`` built through Chunk 3.5 (every table added by whole-table
changes only). Existing databases (the dev DB, any backup restore) are marked current with
``alembic stamp head`` rather than run through this — ``upgrade`` from empty is only for a
fresh DB. Real schema *changes* start at the next revision (Chunk 3.7b: recipes.source_book /
recipes.source_page).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3919bfcbd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd_cents', sa.Float(), nullable=False),
    sa.Column('call_type', sa.Text(), nullable=False),
    sa.Column('context_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_usage_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.Text(), nullable=False),
    sa.Column('section_name', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_name')
    )
    op.create_table('product_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.Text(), nullable=False),
    sa.Column('purchase_label', sa.Text(), nullable=False),
    sa.Column('purchase_qty', sa.Float(), nullable=False),
    sa.Column('purchase_unit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_preseeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_image_path', sa.Text(), nullable=True),
    sa.Column('base_servings', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('times_made', sa.Integer(), nullable=False),
    sa.Column('last_made_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('cuisine', sa.Text(), nullable=True),
    sa.Column('protein', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('preparation', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('session_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.Text(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('total_unit', sa.Text(), nullable=True),
    sa.Column('is_staple', sa.Boolean(), nullable=False),
    sa.Column('already_on_anylist', sa.Boolean(), nullable=False),
    sa.Column('have_it', sa.Text(), nullable=False),
    sa.Column('add_to_list', sa.Boolean(), nullable=False),
    sa.Column('purchase_label', sa.Text(), nullable=True),
    sa.Column('purchase_qty', sa.Float(), nullable=True),
    sa.Column('display_qty', sa.Text(), nullable=True),
    sa.Column('anylist_item_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['planning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_checklist_items_session_id'), ['session_id'], unique=False)

    op.create_table('session_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('scaled_servings', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['planning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_recipes_session_id'), ['session_id'], unique=False)

    op.create_table('shopping_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('anylist_response_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['planning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_history_session_id'), ['session_id'], unique=False)

    op.create_table('store_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'section_name', name='uq_store_section')
    )
    with op.batch_alter_table('store_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_sections_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_sections_store_id'))

    op.drop_table('store_sections')
    with op.batch_alter_table('shopping_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_history_session_id'))

    op.drop_table('shopping_history')
    with op.batch_alter_table('session_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_recipes_session_id'))

    op.drop_table('session_recipes')
    with op.batch_alter_table('session_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_checklist_items_session_id'))

    op.drop_table('session_checklist_items')
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))

    op.drop_table('recipe_ingredients')
    op.drop_table('stores')
    op.drop_table('staples')
    op.drop_table('recipes')
    op.drop_table('product_units')
    op.drop_table('product_sections')
    op.drop_table('planning_sessions')
    op.drop_table('api_usage_resets')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
